### PR TITLE
FIx generate random particles

### LINKED ISSUE #618: Crashes when running "Sample Data > Generate Random Particles"
Click "Sample Data > Generate Random Particles"
Then click OK.
Crashes

### PR DESCRIPTION
**Pull request by cjh1**
Ensure GIL before calling Python API. Fixes #618

### CODE REVIEW

File: tomviz/Utilities.cxx [hunk 1]
```diff
@@ -32,6 +32,7 @@
 #include "vtkPVXMLElement.h"
 #include "vtkPVXMLParser.h"
 #include "vtkPoints.h"
+#include "vtkPython.h"
```
Comment (cquammen) [inline tomviz/Utilities.cxx]: `vtkPython.h` should always be included first. From the comments in `vtkPython.h`:

```
/* We used to try to #undef feature macros that Python.h defines
to avoid re-definition warnings.  However, such warnings usually
indicate a violation of Python's documented inclusion policy:

 "Since Python may define some pre-processor definitions which
  affect the standard headers on some systems, you must include
  Python.h before any standard headers are included."
 (http://docs.python.org/c-api/intro.html#include-files)

To avoid re-definitions warnings, ensure "vtkPython.h" is included
before _any_ headers that define feature macros, whether or not
they are system headers.  Do NOT add any #undef lines here.  */
```

Comment (cjh1) [inline tomviz/Utilities.cxx]: Thanks for catching this, good to know!

**Comment by cryos** [comment]
I would suggest leaving a blank line after the include of vtkPython.h, looks good to me.

**Comment by cquammen** [comment]
Ditto what @cryos said, otherwise `clang-format` will reorder it against your wishes.

**Comment by cjh1** [comment]
@cquammen I have added the space, I think we are ready for merge?

**Comment by cquammen** [comment]
LGTM
