### PR TITLE
Fix transform slowdown

### LINKED ISSUE #273: Slowdown (memory leak?) when using data transforms.
The program gets slower and slower then crashes when using data transforms.

To repeat, simply crop the data. Then delete the crop transform and crop again and delete. Keep repeating and after 2 or three times it will be slow and probably crash.

### PR DESCRIPTION
**Pull request by mathturtle**
@cryos I found it.  I was so sure that refreshHistogram was only called once, but after talking to you I checked in kcachegrind... It was called 11 million times.  I was calling QObject::disconnect on the wrong object (see first commit message) and the number of connections on the signal dataModified was growing exponentially every time something changed the data.  And git blame points straight at me and @utkarshayachit for the lines of code in question.

The second commit in this branch does the event collapsing we talked about with a QTimer.  It also fixed the problem, but it wasn't the real fix.

@Hovden @ElliotPadgett @yijiang1 This should fix #273.

### CODE REVIEW

**Comment by cryos** [comment]
Glad you managed to track it down, like I said the only way I could see that level of allocation/deallocation is if we were calling it thousands (minimum) but millions would do it. Thanks for persevering.

File: tomviz/CentralWidget.cxx [hunk 1]
```diff
@@ -432,7 +437,12 @@ void CentralWidget::setDataSource(DataSource* source)
 
 void CentralWidget::onColorMapUpdated()
 {
-  this->refreshHistogram();
+  this->onDataSourceChanged();
+}
+
+void CentralWidget::onDataSourceChanged()
+{
+  this->Internals->Timer.start();
```
Comment (cryos) [inline tomviz/CentralWidget.cxx]: Might be useful to add a comment explaining this for those not knowing the API so well
// Start (or restart) the one shot timer for delayed histogram refresh.

**Comment by cryos** [comment]
Looks good to me, like I said inline it might be worth adding a comment to make the intent clear (to start/restart the one shot timer). Glad you dug down to the real cause, but squashing many updates down to one or two is useful for many reasons.

**Comment by yijiang1** [comment]
Yup doing multiple data transforms is pretty fast now. :thumbsup:

**Comment by mathturtle** [comment]
I've added the inline comment about what starting that timer in the slot does.
