### PR TITLE
Handle cases where data is added when spreadsheet view is active

### LINKED ISSUE #587: Crash when SpreadSheet view is active and data is loaded
I suspect tomviz is trying to add proxies defined in a `Module` to the spreadsheet view, but have not investigated to confirm.

### PR DESCRIPTION
**Pull request by cquammen**
There was an assumption in LoadDataReaction and
PythonGeneratedDatasetReaction that the current active view is a
Render View. When that isn't the case, visualization modules are not
added correctly, signals and slots are not set up properly, and a
crash might occur. In any case, Tomviz becomes unstable.

Fixed this problem by checking that the active view is a Render View,
and if not, look for one. If there isn't one, create a Render View.

Fixes #587

### CODE REVIEW

**Comment by cquammen** [comment]
Ready for review, @cryos @cjh1 @mathturtle

File: tomviz/ActiveObjects.cxx [hunk 1]
```diff
@@ -121,6 +126,41 @@ void ActiveObjects::setActiveModule(Module* module)
...
+void ActiveObjects::createRenderViewIfNeeded()
+{
+  vtkNew<vtkSMProxyIterator> iter;
+  iter->SetSessionProxyManager(proxyManager());
+  iter->SetModeToOneGroup();
+  for (iter->Begin("views"); !iter->IsAtEnd(); iter->Next()) {
+    vtkSMRenderViewProxy* renderView =
+      vtkSMRenderViewProxy::SafeDownCast(iter->GetProxy());
+    if (renderView) {
+      std::cout << "Found renderview\n";
```
Comment (cjh1) [inline tomviz/ActiveObjects.cxx]: Debug message?

Comment (cquammen) [inline tomviz/ActiveObjects.cxx]: :blush: Removed.
