### PR TITLE
Fix dialog not being shown for python operators

### LINKED ISSUE #1671: Python filters do not open dialog with parameters (first run)
Operators such as Gaussin Blur, Pad, etc run immediately on first execution, this was not the case in the 1.3.1 release. Operators expecting user input should open the dialog before execution.

### PR DESCRIPTION
**Pull request by alesgenova**
Fixes #1671

### CODE REVIEW

File: tomviz/operators/OperatorPython.cxx [hunk 1]
```diff
@@ -257,6 +257,14 @@ void OperatorPython::setJSONDescription(const QString& str)
     }
   }
 
+  // Get the number of parameters
+  QJsonValueRef parametersNode = root["parameters"];
+  if (!parametersNode.isUndefined() && !parametersNode.isNull()) {
+    QJsonArray parametersArray = parametersNode.toArray();
+    QJsonObject::size_type numParameters = parametersArray.size();
+    setNumberOfParameters(numParameters);
```
Comment (mathturtle) [inline tomviz/operators/OperatorPython.cxx]: What happens if the operator doesn't have JSON?  Delete Slices for example has arguments, but no JSON description.

Comment (mathturtle) [reply tomviz/operators/OperatorPython.cxx]: Please test this with https://github.com/OpenChemistry/tomviz/pull/1663 (you may need that to make Delete Slices work right).

Comment (alesgenova) [reply tomviz/operators/OperatorPython.cxx]: The EditOperatorDialog wouldn't be display on first run, but that was the case before as well, since the check was was whether or not a json description was provided.

The new numberOfParameters() method exists alongside the previous arguments() method, so I don't think it should break anything
